export interface PopularMovie {
    id: number,
    adult: Boolean,
    backdrop_path: any,
    genre_ids: Number,
    original_language: String,
    original_title: String,
    overview: String,
    popularity: Number,
    poster_path: String,
    release_date: String,
    title: String,
    video: Boolean,
    vote_average: Number,
    vote_count: Number,
}